// <auto-generated />
namespace Facebook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class David22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(David22));
        
        string IMigrationMetadata.Id
        {
            get { return "201906041729085_David22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
